### Get list from server

GET http://localhost:4000/api/posts

### Post data to server
POST http://localhost:4000/api/posts
# header of the request
Content-Type: application/json


# body of the request, there should be gap between header and body
{
    "title": "The Evolution of E-Commerce: Trends and Innovations",
 
  "content": "E-commerce has come a long way since its inception, constantly evolving to meet the changing needs and preferences of consumers. From the early days of online shopping to the rise of mobile commerce and social commerce, the e-commerce landscape continues to transform. This post examines key trends and innovations shaping the future of e-commerce, including AI-powered personalization, augmented reality shopping experiences, and the growing role of sustainability.",
 
  "author": "Sophia Patel"
}

### update data to server
PUT http://localhost:4000/api/posts/:id
# header of the request
Content-Type: application/json


# body of the request, there should be gap between header and body
{
    "_id":"662b4dfd9a0875389016556a",
    "date": "20/03/2023"
}