### Get list from server

GET http://localhost:4000/api/posts

### Post data to server
POST http://localhost:4000/api/posts
# header of the request
Content-Type: application/json


# body of the request, there should be gap between header and body
{
    "title": "Exploring the Potential of Quantum Computing",
 
  "content": "Quantum computing represents a paradigm shift in computation, promising unprecedented processing power and the ability to solve complex problems at a speed unimaginable with classical computers. With applications ranging from cryptography and drug discovery to optimization and machine learning, quantum computing is poised to revolutionize various industries. This post delves into the fundamentals of quantum computing and its potential impact on the future.",
 
  "author": "Daniel Lee"
}